### ISSUE TITLE
Polluting global?

### ISSUE THREAD

**Issue by spalger** [kevincennis/promise#1]
Looks like promise-js is polluting global objects in a way that's not opt-in.

https://github.com/zloirock/core-js/issues/161#issuecomment-173079010

**Comment by spalger** [comment]
This came to my attentions by way of a user reporting an issue with my library: https://github.com/elastic/elasticsearch-js/issues/345

**Comment by pawelbaranski** [comment]
+1 for solving the issue. We are experiencing the same problem.

I may be wrong but it looks that if any node app that is using a dependencies which are using core-js and promise-js at some point then this app will throw an error and this is some **serious** problem.

**Comment by kevincennis** [comment]
Sorry for the delay. Somehow I never saw the email notifications, and I never really look at this repo anymore.

Commit d2906b5b4c9c253a058994dcdd8b07324839b15d should fix these. Please let me know if you have any other problems. A new version (`0.0.7`) has been deployed to npm.

Apologies for the trouble this has caused. I wrote this a few years ago just to learn a bit about the spec, but it's my bad for neglecting it now that people have been using it.
