### ISSUE TITLE
Prefer `global` instead of `this`

### ISSUE THREAD

**Issue by satazor** [kevincennis/promise#2]
At this [line](https://github.com/kevincennis/promise/blob/37753b831b6daef44a8140ffc30a61bdf6c16a1f/promise.js#L771) you are using `this` to refer to the global context, but `this` defaults to `module.exports` in NodeJS.

This means that the built-in implementation (if available) is not being used. The most correct way is to do `typeof global !== 'undefined' ? global : (typeof self !== 'undefined' ? self : this)`. Explanation: `global` is for NodeJS, `self` is for the web and web-workers, `this` is the fallback.

``` js
// foo.js
console.log(this);
```

In NodeJS it will print `{}` (module.exports).
In the Browser it will print window or undefined if under strict mode.

**Comment by kevincennis** [comment]
Should be all set with b58ef67dd4023139d0aad98ccd0cb60d8a4f9eec
